<a href="https://colab.research.google.com/github/dbsxogh09/AI504/blob/main/ai504_01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))

def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

### Scalars, Vectors, Matrices

In [3]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [5]:
print_obj(a.ndim, "a.ndim")
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")

a.ndim:
0

b.ndim:
1

c.ndim:
2



In [6]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)



### Tensors (N-dimensional array)

In [7]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [8]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)

e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



In [9]:
# Quiz: What is the shape of [[[1], [2], [3]], [[4], [5], [6]]]?
x=np.array([[[1], [2], [3]], [[4], [5], [6]]])
x.shape

(2, 3, 1)

### Defining Numpy arrays

In [10]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a = np.zeros((2, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
a = np.full((2,5), 5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
a = np.random.random((2, 3, 4))
a

array([[[0.33922186, 0.34505728, 0.15929213, 0.83657243],
        [0.24883221, 0.34553906, 0.95044755, 0.28373575],
        [0.58699222, 0.5718834 , 0.12517296, 0.27222821]],

       [[0.05517531, 0.40818321, 0.92683989, 0.00475923],
        [0.60089516, 0.56113931, 0.40677998, 0.6367158 ],
        [0.0244662 , 0.23790427, 0.71034667, 0.79561927]]])

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.arange(10).astype(float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
a = np.arange(10).reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
# Quiz: Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0
x = np.arange(24).reshape((4,3,2)).astype(float)
x

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]], dtype=float16)

### Indexing & Slicing

In [42]:
# Indexing and slicing a vector
a = np.arange(10)
print_obj(a, "a")

print_obj(a[0], "a[0]")
print_obj(a[1], "a[1]")
print_obj(a[-1], "a[-1]")
print_obj(a[-3], "a[-3]")
print_obj(a[-10], "a[-15]")

#print_obj(a[0:10], "a[0:10]")
#print_obj(a[0:], "a[0:]")
#print_obj(a[:10], "a[:10]")
#print_obj(a[:], "a[:]")

#print_obj(a[7:], "a[7:]")
#print_obj(a[:5], "a[:5]")
#print_obj(a[2:5], "a[2:5]")

# Quiz: What is a[-4:]?
# Quiz: What is a[:-8]?

print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")
print_obj(a[2:7:3], "a[2:7:3]")

#print_obj(a[::-1], "a[::-1]")
#print_obj(a[8:5:-1], "a[8:5:-1]")
#print_obj(a[8:5], "a[8:5]")

print_obj(a[-1:1:-3],"a[-1:1:3]")
# Quiz: Create [9, 6, 3] using a.

a:
[0 1 2 3 4 5 6 7 8 9]

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7

a[-15]:
0

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]

a[2:7:3]:
[2 5]

a[-1:1:3]:
[9 6 3]



In [54]:
# Indexing a matrix
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")

# Quiz: How to access the last row?
print_obj(a[-1:],"a[-1:]")
# Quiz: How to access the second column?
print_obj(a[:1],"a[:1]")
# Quiz: How to create [8, 5] using a?
print_obj(a[-1:0:-1,-1],"")

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4

a[-1:]:
[[6 7 8]]

a[:1]:
[[0 1 2]]

:
[8 5]



In [67]:
# Indexing and slicing a 3D tensor
a = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(a, "a")
print_obj(a[2, 1, 0], "a[2, 1, 0]")

# Quiz: What would be a[0]?
# Quiz: What would be a[0, 1]?
# Quiz: Create [[0, 2, 4], [6, 8, 10]]
print_obj(a[0:2,:,0],"")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]:
14

:
[[[ 0  2  4]
  [ 6  8 10]]]



In [68]:
# Conditional indexing
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")

idx = a % 2 == 0
print_obj(idx, "idx")

print_obj(a[idx],"a[idx]")

idx = a > 2
print_obj(a[idx],"a[idx]")

# Quiz: How would you create [3, 4, 5] using a?

a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[ True False]
 [ True False]
 [ True False]]

a[idx]:
[0 2 4]

a[idx]:
[3 4 5]



In [ ]:
# Taking specific elements from a vector
a = np.arange(10)
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")

In [ ]:
# Taking specific elements from a tensor
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:,[0, 2, 3]], "a[idx]")
print_obj(a[[0, 2, 3], :], "a[idx]")
#idx = ((0,0,1,5),(1,2,0,3))
#print_obj(a[idx], "tuple indexing")
#idx = np.array([[0,0,1,5],[1,2,0,3]])
#print_obj(a[idx], "ndarray indexing")

In [73]:
# Ellipsis
#a = np.arange(288).reshape((2,3,2,2,4,-1))
#print_obj(a.shape, "a.shape")

#print_obj(a[1,:,:,:,:,2], "Plain indexing")
#print_obj(a[1,...,2], "Ellipsis")

a = np.arange(20).reshape((2,2,5))
print_obj(a, "a")
print_obj(a.shape, "a.shape")
print_obj(a[1,:,2], "Plain indexing")
print_obj(a[1,...,2], "Ellipsis")

a:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

a.shape:
(2, 2, 5)

Plain indexing:
[12 17]

Ellipsis:
[12 17]



### Math Operations

In [76]:
# Basic operations
a = np.arange(6).reshape((3, 2))
b = np.ones((3, 2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [80]:
# Unary operations
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)")
print_obj(a.sum(axis=1), "a.sum(axis=1)")

print_obj(a.mean(), "a.mean()")
print_obj(a.mean(axis=0), "a.mean(axis=0)")

print_obj(a.max(), "a.max()")
print_obj(a.min(), "a.min()")

# Quiz: Given a = np.arange(24).reshape((2,3,4)), what is the mean of the sum w.r.t to the last dimension?

a:
[[0 1]
 [2 3]
 [4 5]]

a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.mean(axis=0):
[2. 3.]

a.max():
5

a.min():
0



In [81]:
# Vector dot product
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")

a:
[0. 1. 2.]

b:
[1. 1. 1.]

a dot b:
3.0



In [82]:
# Matrix dot product, matrix multiplication
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")
print_obj(a@b, "a @ b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]

a dot b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a @ b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



In [83]:
# Tensor dot product, tensor multiplication
# in general, tensor represents 4 * (3,2) matrices (4 is also can be interpreted as batch dimension)
# mostly, not using dot product for higher order dimensions
a = np.arange(24).reshape((4, 3, 2))
b = np.ones((4, 2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b).shape, "a dot b")
print_obj((a@b).shape, "a @ b")

# Quiz: what would happen if a.shape==(4,3,2) and b.shape==(2,3)?

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

a dot b:
(4, 3, 4, 3)

a @ b:
(4, 3, 3)



### Shape Manipulation

In [85]:
# Reshapes
# can omit using -1. (2,3,-1) is simply interpreted as (2,3,4)
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1))
print_obj(c, "c")

d = a.reshape((6, 4,-1))
print_obj(d, "d")

# Quiz: What would d=a.reshape((6, 4, -1)) look like?

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

d:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]



In [91]:
# Adding an extra dimension
# None gives extra dimension
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")

# Quiz: How to make a = np.ones((3,4)) into shape (3, 1, 1, 4) using reshape and None?
a = np.ones((3,4))
print_obj(a[:, None,None, :], "a[:, None,None, :]")

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]

a[:, None,None, :]:
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]



In [92]:
# Stack, concatenation
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.hstack([a, b]), "a,b hstack")
print_obj(np.hstack([a, b, a]), "a,b hstack")

print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0")
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1")

# Quiz: Would concatenating two tensors whose shapes are (4, 3, 2) and (5, 4, 2) on axis=2 work?
# No, first two sizes are not matched

a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a,b hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]

a,b concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



In [93]:
# Matrix transpose
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



In [ ]:
# Tensor transpose
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")

b = np.transpose(a, [0, 2, 1])
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2])
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

### Broadcasting

In [ ]:
# Vector and scalar
a = np.arange(3)
b = 2.
print_obj(a, "a")

print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

In [ ]:
# Matrix and vector
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

# Quiz: What would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1, 2))?
# First one is not working, broadcasting condition is not met while the second one is working

In [94]:
# Tensor and matrix
# b=np.arange(3) does not meet the broadcasting condition! last dimensions should match
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

#Quiz: How can we use None to do a+b?

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]



### Final Quiz

In [146]:
def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following (assume m is an even number):
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (?, 4n)
# - Linearly transform X with W so that you obtain a matrix Y of shape (?, ?)
# - Put Y through the sigmoid function
# - Obtain the sum of the mean of each column
def foo(M, W):
    (m,n) = M.shape
    print_obj(m,"m")
    print_obj(n,"n")
    a = M[:int(m/2),:]
    print_obj(a,"a")
    b = M[int(m/2):,:]
    print_obj(b,"b")
    c = M[1::2,:]
    print_obj(c,"c")
    d = M[::2,:]
    print_obj(d,"d")


    X = np.hstack([a,b,c,d])
    print_obj(X,"X")

    Y =  np.dot(X,W)
    print_obj(Y,"Y")

    Z = sigmoid(Y)
    col_mean = Z.mean(axis=0)
    print_obj(col_mean,"col_mean")


    return col_mean.sum()
    # return 0.

In [147]:
M = (np.arange(60).reshape((20,3)).astype('float') - 10.) / 10
W = np.arange(36).reshape(12,3).astype('float') / 10.

foo(M,W)

m:
20

n:
3

a:
[[-1.  -0.9 -0.8]
 [-0.7 -0.6 -0.5]
 [-0.4 -0.3 -0.2]
 [-0.1  0.   0.1]
 [ 0.2  0.3  0.4]
 [ 0.5  0.6  0.7]
 [ 0.8  0.9  1. ]
 [ 1.1  1.2  1.3]
 [ 1.4  1.5  1.6]
 [ 1.7  1.8  1.9]]

b:
[[2.  2.1 2.2]
 [2.3 2.4 2.5]
 [2.6 2.7 2.8]
 [2.9 3.  3.1]
 [3.2 3.3 3.4]
 [3.5 3.6 3.7]
 [3.8 3.9 4. ]
 [4.1 4.2 4.3]
 [4.4 4.5 4.6]
 [4.7 4.8 4.9]]

c:
[[-0.7 -0.6 -0.5]
 [-0.1  0.   0.1]
 [ 0.5  0.6  0.7]
 [ 1.1  1.2  1.3]
 [ 1.7  1.8  1.9]
 [ 2.3  2.4  2.5]
 [ 2.9  3.   3.1]
 [ 3.5  3.6  3.7]
 [ 4.1  4.2  4.3]
 [ 4.7  4.8  4.9]]

d:
[[-1.  -0.9 -0.8]
 [-0.4 -0.3 -0.2]
 [ 0.2  0.3  0.4]
 [ 0.8  0.9  1. ]
 [ 1.4  1.5  1.6]
 [ 2.   2.1  2.2]
 [ 2.6  2.7  2.8]
 [ 3.2  3.3  3.4]
 [ 3.8  3.9  4. ]
 [ 4.4  4.5  4.6]]

X:
[[-1.  -0.9 -0.8  2.   2.1  2.2 -0.7 -0.6 -0.5 -1.  -0.9 -0.8]
 [-0.7 -0.6 -0.5  2.3  2.4  2.5 -0.1  0.   0.1 -0.4 -0.3 -0.2]
 [-0.4 -0.3 -0.2  2.6  2.7  2.8  0.5  0.6  0.7  0.2  0.3  0.4]
 [-0.1  0.   0.1  2.9  3.   3.1  1.1  1.2  1.3  0.8  0.9  1. ]
 [ 0.2  0.3  0.4  3.2 

2.7013292476222723